name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg ALPINE_VERSION=3.16.2 src --file src/Dockerfile --tag chonton/ucspi-unix:$(date +%s)
